### ISSUE TITLE
Need to use GPIO with interrupts

### ISSUE THREAD

**Issue by hodiapa** [pabigot/bsp430#20]
Need to use the GPIO ports with their interrupt functions. Which module(or example) you would recommend me to look. Basically I am using the launchpad platform and would like to catch events on the GPIO ports. there is the periph.h and port.h files. But kinda confused which is the correct one to work with. Any suggestions in this regards.
Thanks.

**Comment by pabigot** [comment]
Try examples/bootstrap/button.
