### ISSUE TITLE
Bootloader & ldscript

### ISSUE THREAD

**Issue by hodiapa** [pabigot/bsp430#43]
How can one move the user program to act as a bootloader and then do the firmware upgrade using either of the peripheral interfaces.?

-- Next how to disable loading default ldscript from mspgcc and have a customized ldscript.

Thanks in advance...

**Comment by pabigot** [comment]
Providing a bootloader and firmware updates are out of scope for BSP430.  The capabilities of such advanced features depend on the requirements of a specific application, so they're the responsibility of an application or perhaps an RTOS framework.
